### PR TITLE
extend date range to 1276 and add the correct offset.

### PR DESCRIPTION
**Pull request by minafarideleia**

### CODE REVIEW

**Comment by alhazmy13** [comment]
Nice @minafarideleia

**Review by alhazmy13 — APPROVED** [review]
LGTM

**Comment by mFaridEbrahim** [comment]
@alhazmy13 Thanks

**Comment by msarhan** [comment]
@mFaridEbrahim Thank you very much for your pull request.
v2.0.0 deprecated the use of `UmmalquraGregorianConverter` and instead uses calculations ported from Java 8 which is valid from 1300 H to 1600 H.

Please to check.

**Comment by mFaridEbrahim** [comment]
@msarhan Thanks. I will check

**Pull request closed without merging**
